baseurl = "/"
title = "@rjmuwanga"
theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Robert J Muwanga"
    description = "Robert's personal website"
    keywords = "blog,developer,innovation,R,rlang"
    info = "Husband, Father and Avid Learner of Data Driven Performance"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    hideCredits = false
    hideCopyright = false
    since = 2019

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/robertmuwanga/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/r_muwanga/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/robertmuwanga/"

# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "/about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[menu.main]]
name = "Resume"
weight = 3
url = "/resume/"
