[build] 
command = "hugo" 
context = "production" 
publish = "public" 

[context.production.environment] 
HUGO_VERSION = "0.142.0"
HUGO_ENV = "production"

[build.processing]
  skip_processing = true

